apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: dm90cmVfdXNlcm5hbWU=   # Encodage Base64 du nom d'utilisateur
  password: dm90cmVfbW90X2RlX3Bhc3Nl   # Encodage Base64 du mot de passe
