pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building the application'
                // Ajoutez ici les commandes de build de votre application
                sh 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests'
                // Ajoutez ici les commandes de test de votre application
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying the application'
                // Ajoutez ici les commandes de déploiement sur Kubernetes
                sh 'kubectl apply -f votre-fichier-deployment.yaml'
            }
        }
    }
}
